name: Release Heatlossjs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - "main"

jobs:
  release-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Container Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/heatlossjs
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./heatlossjs
          file: ./heatlossjs/Dockerfile
          platforms: linux/amd64, linux/arm64/v8
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/heatlossjs:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/heatlossjs:buildcache,mode=max